In [3]:
import numpy as np

In [4]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [6]:
b=np.array([5,11])
b

array([ 5, 11])

In [5]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
x = np.dot(Ainv,b)
x

array([1., 2.])

In [9]:
np.dot(A,x)

array([ 5., 11.])

In [10]:
np.dot(A, Ainv)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])