In [3]:
import sys
!{sys.executable} -m pip install --user numpy
import numpy as np

You should consider upgrading via the 'c:\Users\illorenslara.NORTHAMERICA\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


     --------------------------------------- 14.9/14.9 MB 17.2 MB/s eta 0:00:00


In [17]:
a = np.array([20,40,60])
b = np.array([10,20,30])
c = np.array([5,10,15,20])


In [5]:
a+b

array([30, 60, 90])

In [6]:
# Vectors are diff
a - c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
a*b

array([ 200,  800, 1800])

In [ ]:
a/b

array([2., 2., 2.])

In [13]:
scalar=2

In [9]:
list_a = [10,11,12,13,14,15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [10]:
list_as_array = np.array(list_a)
print(list_as_array)

[10 11 12 13 14 15]


In [14]:
# This is not a scalar multiplication, it just repeats the list multiple times
scalar*list_a

[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]

In [15]:
list_as_array*scalar


array([12, 13, 14, 15, 16, 17])

In [18]:
list_as_array+scalar

array([12, 13, 14, 15, 16, 17])

In [19]:
a = np.array([1,2,3, 4, 5])
b = np.array([6,7,8, 9, 10])

In [21]:
dot_product = np.dot(a,b)
print(dot_product)

130


In [22]:
c = np.array([11,12,13, 14, 15])


In [23]:
np.dot(b,a)

130

In [25]:
first_result = np.dot(a,b+c)
second_result = np.dot(a,b) + np.dot(a,c)

print(first_result)
print(second_result)

print (first_result == second_result)

335
335
True


In [28]:
from numpy import linalg as lng

In [30]:
lng.norm(a)

7.416198487095663

In [31]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([60, 70, 80, 90, 100])

In [32]:
lng.norm(a)

74.16198487095663

In [37]:
vector_proj = (np.dot(a,b)/(lng.norm(b)*lng.norm(b)))*b
print(vector_proj)

[23.63636364 27.57575758 31.51515152 35.45454545 39.39393939]


In [44]:
vector_proj = (np.dot(a,b)/np.dot(b,b))*b
print(vector_proj)

[23.63636364 27.57575758 31.51515152 35.45454545 39.39393939]


In [ ]:
# The dot product of the same vector is the as the square of the size of the vector